### ISSUE TITLE
使用方法不够明确 运行后报错

### ISSUE THREAD

**Issue by zidou-kiyn** [wyapx/TechXueAnQuan#2]
ValueError: Unauthorized

**Comment by wyapx** [comment]
登录失败，看看密码是不是错了

**Comment by zidou-kiyn** [comment]
ERROR:root:Unknown Error:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\TechXueAnQuan-main\main.py", line 82, in main
    if not await do_it(name, passwd):
  File "C:\Users\Administrator\Desktop\TechXueAnQuan-main\main.py", line 61, in do_it
    spid = await get_unfinish_spid(login_resp.cookies)
  File "C:\Users\Administrator\Desktop\TechXueAnQuan-main\main.py", line 29, in get_unfinish_spid
    for hw in await get_homework(cookie):
  File "C:\Users\Administrator\Desktop\TechXueAnQuan-main\utils\api.py", line 33, in get_homework
    raise ValueError(resp.status)
ValueError: Unauthorized


检查过了 密码没有问题

**Comment by huujiee** [comment]
1，确认密码没有错，登录流程200，login_resp.cookies里面没有值
2，请求这个api/v1/homework/homeworklist接口的时候，返回401

**Comment by huujiee** [comment]
可能是接口变了？

> 1，确认密码没有错，登录流程200，login_resp.cookies里面没有值
> 2，请求这个api/v1/homework/homeworklist接口的时候，返回401

可能是接口变了？

**Comment by wyapx** [comment]
有可能变了
最近有点忙，到时候再抓一次包看看

**Comment by Azhuai** [comment]
域名改了，得重新弄了
